export default defineAppConfig({
  title: 'clhs 短網址',
  description: '一個簡單、快速、安全的短網址服務。',
  image: 'https://s.clhs.dev/banner.png',
  previewTTL: 300, // 5 minutes
  slugRegex: /^[a-z0-9]+(?:-[a-z0-9]+)*$/i,
  reserveSlug: [
    'dashboard',
    'privacy',
    'terms',
    'api',
    'admin',
    'auth',
    'login',
    'logout',
    'assets',
    'public',
    'static',
    'robots.txt',
    'sitemap.xml',
    'favicon.ico',
    'about',
    'contact',
    'support',
    'help',
  ],
})
